// <auto-generated />
using System;
using BlueSkyTravel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueSkyTravel.Migrations
{
    [DbContext(typeof(BlueSkyContext))]
    partial class BlueSkyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueSkyTravel.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirlineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fare")
                        .HasColumnType("float");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineName = "WCCI AIR",
                            ArrivalDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Fare = 426.0,
                            FlightNumber = "WCCI-2020"
                        });
                });

            modelBuilder.Entity("BlueSkyTravel.Models.ForFun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fare")
                        .HasColumnType("float");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ForFuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventTime = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Fare = 100.0,
                            IsApproved = false,
                            Location = "Paris, France",
                            Name = "Disneyland"
                        });
                });

            modelBuilder.Entity("BlueSkyTravel.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<double>("NightlyRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "221B Baker Street",
                            CheckIn = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOut = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            NightlyRate = 150.0
                        });
                });

            modelBuilder.Entity("BlueSkyTravel.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TravelDateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TravelDateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Itinerary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 1500.0,
                            Destination = "London, UK",
                            TravelDateFinish = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            TravelDateStart = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlueSkyTravel.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("VoteChoice")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VoteChoice = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
